name: latimes
channels: 
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip=18.0
  - altair=2.2.2
  - click=7.0
  - click-plugins=1.0.4
  - cligj=0.5.0
  - descartes=1.1.0
  - fiona=1.8.3
  - conda-forge/label/dev::geopandas=0.4.0
  - ipykernel=5.1.0
  - ipython=7.2.0
  - ipython_genutils=0.2.0
  - kiwisolver=1.0.1
  - matplotlib=3.0.2
  - nbconvert=5.4.0
  - nbformat=4.4.0
  - notebook=5.7.2
  - numpy=1.15.4
  - pandas=0.23.4
  - pandocfilters=1.4.2
  - pyzmq=17.1.2
  - rtree=0.8.3
  - shapely=1.6.4
  - terminado=0.8.1
  - toolz=0.9.0
  - tornado=5.1.1
  - traitlets=4.3.2
  - pip:
    - attrs==18.2.0
    - backcall==0.1.0
    - bleach==3.0.2
    - cycler==0.10.0
    - decorator==4.3.0
    - defusedxml==0.5.0
    - entrypoints==0.2.3
    - jedi==0.13.1
    - jinja2==2.10
    - jsonschema==2.6.0
    - markupsafe==1.1.0
    - mistune==0.8.4
    - munch==2.3.2
    - parso==0.3.1
    - pexpect==4.6.0
    - pickleshare==0.7.5
    - prometheus-client==0.5.0
    - prompt-toolkit==2.0.7
    - ptyprocess==0.6.0
    - pygments==2.3.0
    - pyparsing==2.3.0
    - pyproj==1.9.5.1
    - python-dateutil==2.7.5
    - pytz==2018.7
    - send2trash==1.5.0
    - six==1.11.0
    - testpath==0.4.2
    - typing==3.6.6
    - wcwidth==0.1.7
    - webencodings==0.5.1
